import React from 'react'
import styled from 'styled-components'
const IMG=styled.div`
  display: flex;
  align-items: center;
  justify-content: space-around;
  flex-wrap: wrap;
  background-color: antiquewhite;
  height: 1440px;

`
const Kollam = () => {
  return (
    <div>

      <div>
        <img width={"100%"} height={"600px"} src="https://s3.india.com/wp-content/uploads/2024/11/When-Is-The-Perfect-Time-To-Visit-Kollam-Kerala_-Find-Out.jpg##image/jpg" alt="" />
      </div>
      <h1>ABOUT KOLLAM</h1>
      <p>Kollam (Malayalam: [kolːɐm] ⓘ; also known by its former name Quilon[a]), is an ancient seaport and the fourth largest city in the Indian state of Kerala. Located on the southern tip of the Malabar Coast of the Arabian Sea, the city is on the banks of Ashtamudi Lake and is 71 kilometers (44 mi) northwest of the Thiruvananthapuram.[7] Kollam is one of India's oldest continuously inhabited cities,[8][9] with evidence of habitation stretching back to the megalithic; the city has also been a maritime entrepôt millennia, the earliest attestation of which dates back to the Phoenicians and Romans.[10] It is the southern gateway to the Backwaters of Kerala,[11] and is known for its cashew processing, coir manufacturing, and tourism industries.[12][13]

Kollam has a strong commercial reputation since ancient times. The Arabs, Phoenicians, Chinese, Ethiopians, Syrians, Jews, Chaldeans and Romans have all engaged in trade at the port of Kollam for millennia.[14] As a result of Chinese trade, Kollam was mentioned by Ibn Battuta in the 14th century as one of the five Indian ports he had seen during the course of his twenty-four-year travels.[15][16] Desinganadu's rajas exchanged embassies with Chinese rulers while there was a flourishing Chinese settlement at Kollam. In the ninth century, on his way to Canton, China, Persian merchant Sulaiman al-Tajir found Kollam to be the only port in India visited by huge Chinese junks. Marco Polo, the Venetian traveller, who was in Chinese service under Kublai Khan in 1275, visited Kollam and other towns on the west coast, in his capacity as a Chinese mandarin.[17] Kollam is also home to one of the seven churches that were established by St Thomas as well as one of the 10 oldest mosques believed to be found by Malik Deenar in Kerala. Roman Catholic Diocese of Quilon is the first diocese in India.[18]

V. Nagam Aiya in his Travancore State Manual records that in 822 AD two East Syriac bishops Mar Sabor and Mar Proth, settled in Quilon with their followers. Two years later the Malabar Era began (824 AD) and Quilon became the premier city of the Malabar region ahead of Travancore and Cochin.[19] Kollam Port was founded by Mar Sabor at Tangasseri in 825 as an alternative to reopening the inland seaport of Kore-ke-ni Kollam near Backare (Thevalakara), which was also known as Nelcynda and Tyndis to the Romans and Greeks and as Thondi to the Tamils.[19] Thambiran Vanakkam printed in 20 October 1578 at Kollam was the first book to be published in an Indian language.[20]

Kollam city corporation received ISO 9001:2015 certification for municipal administration and services.[21] As per the survey conducted by the Economist Intelligence Unit (EIU) based on urban area growth during January 2020, Kollam became the tenth fastest growing city in the world with a 31.1% urban growth between 2015 and 2020.[22] It is a coastal city and on the banks of Ashtamudi Lake. The city hosts the administrative offices of Kollam district and is a prominent trading city for the state. The proportion of females to males in Kollam city is second highest among the 500 most populous cities in India.[23] Kollam is one of the least polluted cities in India.[24]

During the later stages of the rule of the Chera monarchy in Kerala, Kollam emerged as the focal point of trade and politics. Kollam continues to be a major business and commercial centre in Kerala. Four major trading centers around Kollam are Kottarakara, Punalur, Paravur, and Karunagapally. Kollam appeared as Palombe in Mandeville's Travels, where he claimed it contained a Fountain of Youth.</p>
<h3>History</h3>
<p>As the ancient city of Quilon, Kollam was a flourishing port during the Pandya dynasty (c. 3rd century BC–12th century), and later became the capital of the independent Venad or the Kingdom of Quilon on its foundation in c. 825. Kollam was considered one of the four early entrepots in global sea trade during the 13th century, along with Alexandria and Cairo in Egypt, the Chinese city of Quanzhou, and Malacca in the Malaysian archipelago.[29] It seems that trade at Kollam seems to have flourished right into the Medieval period as in 1280, there is instance of envoys of Yuan China coming to Kollam for establishing relations between the local ruler and China.[30]

Pandya rule
The ancient political and cultural history of Kollam was almost entirely independent from that of the rest of Kerala. The Chera dynasty governed the area of Malabar Coast between Alappuzha in the south to Kasaragod in the north. This included Palakkad Gap, Coimbatore, Salem, and Kolli Hills. The region around Coimbatore was ruled by the Cheras during Sangam period between c. first and the fourth centuries CE and it served as the eastern entrance to the Palakkad Gap, the principal trade route between the Malabar Coast and Tamil Nadu.[31] However the southern region of present-day Kerala state (The coastal belt between Thiruvananthapuram and Alappuzha) was under Ay dynasty, who was more related to the Pandya dynasty of Madurai than Cheras.[32]

Along with (Muziris and Tyndis), Quilon was an ancient seaport on the Malabar Coast of India from the early centuries before the Christian era. Kollam served as a major port city for Pandya dynasty on the western coast while Kulasekharapatnam served Pandyas on the eastern coast. The city had a high commercial reputation from the days of the Phoenicians and Ancient Romans. Pliny the Elder (23–79 AD) mentions Greek ships anchored at Muziris and Nelcynda. There was also a land route over the Western Ghats. Spices, pearls, diamonds, and silk were exported to Egypt and Rome from these ports. Pearls and diamonds came to the Chera Kingdom from Ceylon and the southeastern coast of India, then known as the Pandyan Kingdom.

Cosmas Indicopleustes, a Greek Nestorian sailor,[33] in his book the Christian Topography[34] who visited the Malabar Coast in 550, mentions an enclave of Christian believers in Male (Malabar Coast). He writes, "In the island of Tabropane (Ceylon), there is a church of Christians, and clerics and faithful. Likewise at Male, where the pepper grows, and in the farming community of Kalliana (Kalliankal at Nillackal) there is also a bishop consecrated in Persia in accordance with the Nicea Sunnahadose of 325 AD."[35] The Nestorian Patriarch Jesujabus, who died in 660 AD, mentions Kollam in his letter to Simon, Metropolitan of Persia.

Kollam is also home to one of the oldest mosques in Indian subcontinent. According to the Legend of Cheraman Perumals, the first Indian mosque was built in 624 AD at Kodungallur with the mandate of the last the ruler (the Cheraman Perumal) of Chera dynasty, who left from Dharmadom to Mecca and converted to Islam during the lifetime of Muhammad (c. 570–632).[36][37][38][39] According to Qissat Shakarwati Farmad, the Masjids at Kodungallur, Kollam, Madayi, Barkur, Mangalore, Kasaragod, Kannur, Dharmadam, Panthalayini, and Chaliyam, were built during the era of Malik Dinar, and they are among the oldest Masjids in Indian subcontinent.[40] It is believed that Malik Dinar died at Thalangara in Kasaragod town</p>
<h4>Capital of Venad (9th to 12th centuries)</h4>
<p>The port at Kollam, then known as Quilon, was founded in 825 by the Nestorian Christians Mar Sabor and Mar Proth with sanction from Ayyanadikal Thiruvadikal, the king of the independent Venad or the State of Quilon, a feudatory under the Chera kingdom.[42][43][44]

It is believed that Mar Sapor Iso also proposed that the Chera king create a new seaport near Kollam in lieu of his request that he rebuild the almost vanished inland seaport at Kollam (kore-ke-ni) near Backare (Thevalakara), also known as Nelcynda and Tyndis to the Romans and Greeks and as Thondi to the Tamils, which had been without trade for several centuries because the Cheras were overrun by the Pallavas in the sixth century, ending the spice trade from the Malabar coast. This allowed the Nestorians to stay in the Chera kingdom for several decades and introduce the Christian faith among the Nampoothiri Vaishnavites and Nair sub-castes in the St. Thomas tradition, with the Syrian liturgy as a basis for the Doctrine of the Trinity, without replacing the Sanskrit and Vedic prayers.[45] The Tharisapalli plates presented to Maruvan Sapor Iso by Ayyanadikal Thiruvadikal granted the Christians the privilege of overseeing foreign trade in the city as well as control over its weights and measures in a move designed to increase Quilon's trade and wealth.[44][46] The two Christians were also instrumental in founding Christian churches with Syrian liturgy along the Malabar coast, distinct from the ancient Vedic Advaitam propounded by Adi Shankara in the early ninth century among the Nampoothiri Vaishnavites and Nair Sub Castes, as Malayalam was not accepted as a liturgical language until the early 18th century.

Thus began the Malayalam Era, known as Kolla Varsham after the city, indicating the importance of Kollam in the ninth century.[44] The Persian merchant Soleyman of Siraf visited Malabar in the ninth century and found Quilon to be the only port in India used by the huge Chinese ships as their transshipment hub for goods on their way from China to the Persian Gulf. The rulers of Kollam (formerly called 'Desinganadu') had trade relations with China and exchanged embassies. According to the records of the Tang dynasty (618–913),[47] Quilon was their chief port of call before the seventh century. The Chinese trade decreased about 600 and was again revived in the 13th century. Mirabilia Descripta by Bishop Catalani gives a description of life in Kollam, which he saw as the Catholic bishop-designate to Kollam, the oldest Catholic diocese in India. He also gives[48] true and imaginary descriptions of life in 'India the Major' in the period before Marco Polo visited the city. Sulaiman al-Tajir, a Persian merchant who visited Kerala during the reign of Sthanu Ravi Varma (9th century CE), records that there was extensive trade between Kerala and China at that time, based at the port of Kollam.</p>
<h4>Kollam as "Colombo" in the Catalan Atlas (1375)</h4>
<p>In the 13th century CE, Maravarman Kulasekara Pandyan I, a Pandya ruler fought a war in Venad and captured the city of Kollam.[54] The city appears on the Catalan Atlas of 1375 CE as Columbo and Colobo. The map marks this city as a Christian city, ruled by a Christian ruler.[50]

The text above the picture of the king says:

Açí seny[o]reja lo rey Colobo, christià. Pruvíncia de Columbo
(Here reigns the Lord King Colobo, Christian, Province of Columbo).[50]

The city was much frequented by the Genoese merchants during the 13th-14th centuries CE, followed by the Dominican and Franciscan friars from Europe. The Genoese merchants called the city Colõbo/Colombo.

The city was founded in 825 by Maruvān Sapir Iso, a Persian East Syriac Christian merchant, and was also Christianized early by the Saint Thomas Christians. In 1329 CE Pope John XXII established Kollam / Columbo as the first and only Roman Catholic bishopric on the Indian subcontinent, and appointed Jordan of Catalonia, a Dominican friar, as the diocese's first bishop of the Latin sect.[50] The Pope's Latin scribes assigned the name "Columbum" to Columbo.

According to a book authored by Ilarius Augustus, published April, 2021 ('Christopher Columbus: Buried deep in Latin the Indian origin of the great explorer from Genoa'), the words Columbum, Columbus and Columbo appear for the first time in a notarial deed (lease contract) of a certain Mousso in Genoa in 1329 CE. These words appear in the form of a toponym. The author then shows, through the Latin text of several other notarial deeds and the documents on church history, how Christopher Columbus - also carrying the same toponym.- was part of Mousso's family, and hence of the Indian lineage (although born in Genoa).</p>
<h4>Portuguese, Dutch and British Trade and Influences (16th to 18th centuries)</h4>
<p>The Portuguese arrived at Kappad Kozhikode in 1498 during the Age of Discovery, thus opening a direct sea route from Europe to India.[56] They were the first Europeans to establish a trading center in Tangasseri, Kollam in 1502, which became the centre of their trade in pepper.[57] In the wars with the Moors/Arabs that followed, the ancient church (temple) of St Thomas Tradition at Thevalakara was destroyed. In 1517, the Portuguese built the St. Thomas Fort in Thangasseri, which was destroyed in the subsequent wars with the Dutch. In 1661, the Dutch East India Company took possession of the city. The remnants of the old Portuguese Fort, later renovated by the Dutch, can be found at Thangasseri. In the 18th century, Travancore conquered Kollam, followed by the British in 1795.[58] Thangasseri remains today as an Anglo-Indian settlement, though few Anglo-Indians remain. The Infant Jesus Church in Thangasseri, an old Portuguese-built church,[59] remains as a memento of the Portuguese rule of the area.[6</p>
<p><h4>Battle of Quilon </h4>
Main article: Battle of Quilon

Kollam fort in 1756 after it had passed from Portuguese rule to the Dutch.
The Battle of Quilon was fought in 1809 between a troop of the Indian kingdom of Travancore led by the then Dalawa (prime minister) of Travancore, Velu Thampi Dalawa and the British East India Company led by Colonel Chalmers at Cantonment Maidan in Quilon. The battle lasted for only six hours[63] and was the result of the East India Company's invasion of Quilon and their garrison situated near the Cantonment Maidan. The company forces won the battle while all the insurrectionist who participated in the war were court-martialed and subsequently hanged at the maidan.[64]

 <h4>Travancore Rule</h4>
In the early 18th century CE, the Travancore royal family adopted some members from the royal family of Kolathunadu based at Kannur, and Parappanad based in present-day Malappuram district.[65] Later, Venad Kingdom was completely merged with the Kingdom of Travancore during the reign of Marthanda Varma and Kollam remained as the capital of Travancore Kingdom. Later on, the capital of Travancore was relocated to Thiruvananthapuram.

Travancore became the most dominant state in Kerala by defeating the powerful Zamorin of Kozhikode in the battle of Purakkad in 1755.[66] The Government Secretariat was also situated in Kollam till the 1830s. It was moved to Thiruvananthapuram during the reign of Swathi Thirunal.[67]

 <h4>Excavation at Kollam Port seabed</h4>

Plan of Kollam 1850s
Excavations are going on at Kollam Port premises since February 2014 as the team has uncovered arrays of antique artifacts, including Chinese porcelain and coins.[68] A Chinese team with the Palace Museum, a team from India with Kerala Council for Historical Research (KCHR) discovered Chinese coins and artifacts that show trade links between Kollam and ancient China</p>
<h3>Geography</h3>
<p>Kollam city is bordered by the panchayats of Neendakara and Thrikkaruva to the north, Mayyanad to the south, and Thrikkovilvattom and Kottamkara to the east, and by the Laccadive Sea to the west. Ashtamudi Lake is in the heart of the city. The city is about 71 km (44 mi) away from Thiruvananthapuram, 140 km (87 mi) away from Kochi and 350 km (220 mi) away from Kozhikode. The National Waterway 3 and Ithikkara river are two important waterways passing through the city. The 7.7 km (4.8 mi) long Kollam Canal is connecting Paravur Lake ans Ashtamudi Lake. The Kallada river, another river that flows through the suburbs of the city, empties into Ashtamudi Lake, while the Ithikkara river runs to Paravur Kayal. Kattakayal, a freshwater lake in the city, connects another water-body named Vattakkayal with Lake Ashtamudi.[70][71][72] In March 2016, IndiaTimes selected Kollam as one of the nine least polluted cities on earth to which anybody can relocate.[73] Kollam is one among the top 10 most welcoming places in India for the year 2020, according to Booking.com's traveller review awards.[74]

Kollam is an ancient trading town – trading with Romans, Chinese, Arabs, and other Orientals – mentioned in historical citations dating back to Biblical times and the reign of Solomon, connecting with Red Sea ports of the Arabian Sea (supported by a find of ancient Roman coins).[75][76] There was also internal trade through the Aryankavu Pass in Schenkottah Gap connecting the ancient town to Tamil Nadu. The overland trade in pepper by bullock cart and the trade over the waterways connecting Allepey and Cochin established trade linkages that enabled it to grow into one of the earliest Indian industrial townships. The rail links later established to Tamil Nadu supported still stronger trade links. The factories processing marine exports and the processing and packaging of cashewnuts extended its trade across the globe.[77] It is known for cashew processing and coir manufacturing. Ashtamudi Lake is considered the southern gateway to the backwaters of Kerala and is a prominent tourist destination at Kollam. The Kollam urban area includes suburban towns such as Paravur in the south, Kundara in the east and Karunagapally in the north of the city. Other important towns in the city suburbs are Eravipuram, Kottiyam, Kannanallur, and Chavara.</p>
<h4>Economy</h4>
<p>The city life of Kollam has changed in the last decade. In terms of economic performance and per capita income, Kollam city is in fifth position from India and third in Kerala.[100] Kollam is famous as a city with excellent export background.[101] 5 star, 4 star and 3 star hotels, multi-storied shopping malls, branded jewellery, textile showrooms and car showrooms have started operations in the city and suburbs. Kollam was the third city in Kerala (after Kozhikode and Kochi) to adopt the shopping mall culture. Kollam district ranks first in livestock wealth in the state. Downtown Kollam is the main CBD of Kollam city.

Dairy farming is fairly well developed. Also there is a chilling plant in the city. Kollam is an important maritime and port city. Fishing has a place in the economy of the district. Neendakara and Sakthikulangara villages in the suburbs of the city have fisheries. An estimated 134,973 persons are engaged in fishing and allied activities. Cheriazheekkal, Alappad, Pandarathuruthu, Puthenthura, Neendakara, Thangasseri, Eravipuram and Paravur are eight of the 26 important fishing villages. There are 24 inland fishing villages. The Government has initiated steps for establishing a fishing harbour at Neendakara. Average fish landing is estimated at 85,275 tonnes per year. One-third of the state's fish catch is from Kollam. Nearly 3000 mechanised boats are operating from the fishing harbour. FFDA and VFFDA promote fresh water fish culture and prawn farming respectively. A fishing village with 100 houses is being built at Eravipuram. A prawn farm is being built at Ayiramthengu, and several new hatcheries are planned to cater to the needs of the aquaculturists. Kerala's only turkey farm and a regional poultry farm are at Kureepuzha.[102]

There are two Central Government industrial operations in the city, the Indian Rare Earths, Chavara and Parvathi Mills Ltd., Kollam. Kerala Ceramics Ltd. in Kundara, Kerala Electrical and Allied Engineering Company in Kundara, Kerala Premo Pipe factory in Chavara, Kerala Minerals and Metals Limited in Chavara and United Electrical Industries in Kollam are Kerala Government-owned companies. Other major industries in the private/cooperative sector are Aluminium Industries Ltd. in Kundara, Thomas Stephen & Co. in Kollam, Floorco in Paravur and Cooperative Spinning Mill in Chathannoor.[103] The beach sands of the district have concentrations of such heavy minerals as Ilmenite, Rutile, Monosite and Zircon, which offer scope for exploitation for industrial purposes.


Technopark Kollam
Besides large deposits of China clay in Kundara, Mulavana and Chathannoor, there are also lime-shell deposits in Ashtamudi Lake and Bauxite deposits in Adichanallur.[104]

Known as the "Cashew Capital of the World", Kollam is noted for its traditional cashew business and is home to more than 600 cashew-processing units. Every year, about 800,000 tonnes of raw cashews are imported into the city for processing[105] and an average of 130,000 tonnes of processed cashews are exported to various countries worldwide.[106] The Cashew Export Promotion Council of India (CEPCI) expects a rise in exports to 275,000 tonnes by 2020, an increase of 120 per cent over the current figure.[107] The Kerala State Cashew Development Corporation Limited (KSCDC) is situated at Mundakkal in Kollam city. The company owns 30 cashew factories all across Kerala. Of these, 24 are located in Kollam district.[108][109]

Kollam is one of many seafood export hubs in India with numerous companies involved in the sector. Most of these are based in the Maruthadi, Sakthikulangara, Kavanad, Neendakara, Asramam, Kilikollur, Thirumullavaram and Uliyakovil areas of the city.[110][111] Capithans, Kings Marine Exporters, India Food Exports and Oceanic Fisheries are examples of seafood exporters</p>

 <h1>MAJOR ATTRACTIONS</h1>
<IMG>
<img  height={"450px"} width={"400px"}style={{marginTop:"40px"}} src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRafrfspErdTrdONVKC4-ywn0ATBl0-n41yiA&s" alt="" />
    <img  height={"450px"} width={"400px"}style={{marginTop:"40px"}} src="https://i.ytimg.com/vi/FuJcyRVxVt0/sddefault.jpg" alt="" />
    <img  height={"450px"} width={"400px"}style={{marginTop:"40px"}} src="https://www.alightindia.com/cdn/uploads/postimages/ORIGINAL/Astamudi%20Lake%20Kerala--2d5abe.jpg" alt="" />
    <img  height={"450px"} width={"400px"}style={{marginTop:"40px"}} src="https://i.ytimg.com/vi/-U_1WqHnBVI/maxresdefault.jpg" alt="" />
    <img  height={"450px"} width={"400px"}style={{marginTop:"40px"}} src="https://i.ytimg.com/vi/1pT-nTMPID8/maxresdefault.jpg" alt="" />
    <img  height={"450px"} width={"400px"}style={{marginTop:"40px"}} src="https://i.ytimg.com/vi/Gfz5zkuX4rA/maxresdefault.jpg" alt="" />
</IMG>
<div style={{height:"350px",paddingLeft:"500px",paddingTop:"100px",backgroundColor:'red'}}>
      <h2>contact us for more informations</h2>

    </div>

    
    </div>
  )
}

export default Kollam
