import React from 'react'
import styled from 'styled-components'
const IMG=styled.div`
display: flex;
align-items: center;
justify-content: space-around;
flex-wrap: wrap;
background-color: antiquewhite;
height: 1400px;
`
const Trivandrum = () => {
  return (
    <div>
      <div>
<img width={"100%"} height={"600px"} src="https://tds.indianeagle.com/wp-content/uploads/2022/07/Places-to-Visit-in-Thiruvananthapuram.png" alt="" />
      </div>
      <h1>ABOUT THIRUVANANDHAPURAM</h1>
      <p>Thiruvananthapuram (/ˌtɪruːvəˌnʌntəˈpʊərəm/ TIRR-oo-və-NUN-təp-OOR-əm; Malayalam: [t̪iɾuʋɐnɐn̪d̪ɐpuɾɐm] ⓘ), formerly known as Trivandrum,[10] is the capital city of the Indian state of Kerala. It is the largest and most populous city in Kerala[11] and it is also a major port city. Thiruvananthapuram is where Asia's first space university, the Indian Institute of Space Science and Technology[12] located, and India's first IT park, Technopark Thiruvananthapuram is in Thiruvananthapuram. The city also includes India’s first deep-water trans-shipment port, the Vizhinjam International Seaport Thiruvananthapuram,[13] as well as the Sree Padmanabhaswamy Temple, known as the richest temple in the world.[14] Thiruvananthapuram is where India's space program began, with the Vikram Sarabhai Space Centre and the headquarters of Liquid Propulsion Systems Centre located here. Thiruvananthapuram is also known for its cultural heritage, being associated with the musical contributions of Swathi Thirunal Rama varma and the artistic legacy of painter Raja Ravi Varma.Notable beaches in Thiruvananthapuram include Kovalam, Varkala, Shankumugham Beach ,and Poovar.The encompassing urban agglomeration population is around 1.68 million.[5] Located on the west coast of India near the extreme south of the mainland, Thiruvananthapuram is a major information technology hub in Kerala and contributes 55% of the state's software exports as of 2016.[15][16] Referred to by Mahatma Gandhi as the "Evergreen city of India",[17][1] the city is characterised by its undulating terrain of low coastal hills.[18]

The present regions that constitute Thiruvananthapuram were ruled by the Ays who were related to feudatories of the Chera dynasty.[19] In the 12th century, it was conquered by the Kingdom of Venad.[19] In the 18th century, the king Marthanda Varma expanded the territory, founded the princely state of Travancore and made Thiruvananthapuram its capital.[20] Travancore became the most dominant state in Kerala by defeating the powerful Zamorin of Kozhikode in the battle of Purakkad in 1755.[21] Following India's independence in 1947, Thiruvananthapuram became the capital of Travancore–Cochin state and remained so until the new Indian state of Kerala was formed in 1956.[22]


ULCV MSC Claude Girardet is the largest vessel to berth in South Asia.[23] It was seen near the beaches of Thiruvananthapuram prior to its arrival at Vizhinjam International Seaport Thiruvananthapuram
Thiruvananthapuram is a notable academic and research hub and home to the University of Kerala, APJ Abdul Kalam Technological University, the regional headquarters of Indira Gandhi National Open University, and many other schools and colleges. Thiruvananthapuram is also home to research centers such as the National Institute for Interdisciplinary Science and Technology, Indian Space Research Organisation's Vikram Sarabhai Space Centre, the Indian Institute of Space Science and Technology, National Centre for Earth Science Studies and a campus of the Indian Institutes of Science Education and Research.[24] The city is home to media institutions like Toonz Animation India and Tata Elxsi Ltd, and also to Chitranjali Film Studio, one of the first film studios in Malayalam Cinema, and Kinfra Film and Video Park at Kazhakoottom, which is India's first Infotainment industrial park.[25]

Being India's largest city in the deep south, it is strategically prominent and hosts the Southern Air Command headquarters of the Indian Air Force, the Thumba Equatorial Rocket Launching Station and the upcoming Vizhinjam International Seaport. Thiruvananthapuram is a major tourist centre, known for the Padmanabhaswamy Temple, the beaches of Kovalam and Varkala, the backwaters of Poovar and Anchuthengu and its Western Ghats tracts of Ponmudi and the Agastya Mala. In 2012, Thiruvananthapuram was named the best Kerala city to live in, by a field survey conducted by The Times of India.[26] In 2013, the city was ranked the fifteenth best city to live in India, in a survey conducted by India Today.[27] Thiruvananthapuram was ranked the best Indian city for two consecutive years, 2015 and 2016, according to the Annual Survey of India's City-Systems (ASICS) conducted by the Janaagraha Centre for Citizenship and Democracy.[28] The city was also selected as the best governed city in India in a survey conducted by Janaagraha Centre for citizenship and democracy in 2017.</p>
 
 <h3>History</h3>
 <p>Thiruvananthapuram is a relatively modern region with trading traditions dating back to 1000 BCE.[33][34] It is believed that the ships of King Solomon landed in a port called Ophir (now Poovar) in Thiruvananthapuram in 1036 BCE.[35][36] The city was the trading post of spices, sandalwood and ivory.[37] However, the ancient political and cultural history of the city was almost entirely independent from that of the rest of Kerala.

The Chera dynasty governed the area of Malabar Coast between Alappuzha in the south to Kasaragod in the north. This included Palakkad Gap, Coimbatore, Salem, and Kolli Hills. The region around Coimbatore was ruled by the Cheras during Sangam period between c. first and the fourth centuries CE and it served as the eastern entrance to the Palakkad Gap, the principal trade route between the Malabar Coast and Tamil Nadu.[38] However the southern region of present-day Kerala state (The coastal belt between Thiruvananthapuram and Alappuzha) was under Ay dynasty, who was more related to the Pandya dynasty of Madurai.[39]

The early rulers of the city were the Ays. Vizhinjam, which is now a region in the present-day Thiruvananthapuram, was the capital of the Ay dynasty.[40] Vizhinjam was an important port city from as early as the second century BC.[41][42] During the Ay dynasty's rule, Thiruvananthapuram witnessed many battles in which the Chola and Pandyan dynasties attempted to capture the port town.[43][44]

After the death of king Vikramaditya Varaguna in 925 AD, the glory of the Ays departed and almost all their territories became part of the Chera dynasty.[45][19] During the tenth century, the Cholas attacked and sacked Vizhinjam and surrounding regions.[19] The port in Vizhinjam and the historic education center of Kanthalloor Sala were also destroyed by Cholas during this period.[46][47] A branch of the Ay family, which had controlled the Padmanabhaswamy Temple, merged with the Kingdom of Venad in the 12th century.[19]


A map of Malabar Coast drawn by Homann Heirs in 1733. At that time, Travancore was only a small territory wedged between Kollam and Kanyakumari, as shown in the map (Present-day districts of Thiruvananthapuram and Kanyakumari only). It was in the latter half of the 18th century, that Travancore inherited the kingdoms up to Cochin and became a powerful kingdom, and Thiruvananthapuram became a major city of Kerala.
Present-day Thiruvananthapuram city, district, and Kanyakumari district, were parts of the Ay dynasty during ancient and medieval ages, which was a Tamil kingdom based in the southernmost part of the Indian subcontinent.[48] Ay kingdom had experienced attacks and conquests by Cholas and Pandyas in various periods.[48] Later it became a part of Venad in late Middle Ages, which was eventually expanded as the powerful kingdom of Travancore in 18th century CE.[48] The Tamil-Dravidian kind of architecture is also found in Padmanabhaswamy temple, which makes it distinct and unique from the architectural style of temples in northern and central parts of Kerala.[48]


Thambiran Vanakkam was printed at Kollam, the capital of Venad in 1578, during the Portuguese Era. It holds the record of the first book printed in any Indian language. It was written in the language Lingua Malabar Tamul which was spoken in Kerala during the medieval period.

The official language of Kerala, based at Kollam, was also identified as Tamil, by the natives of Kerala in those times.[49][50] and the Chola dynasty,[51][52][53] The place names, the dialects of Malayalam spoken, and the customs that exist in Kerala today still reveal a close relationship with Tamil heritage.[54]

In the early 18th century CE, the Travancore royal family adopted some members from the royal family of Kolathunadu based at Kannur.[55] Then, Marthanda Varma who inherited the Kingdom of Venad expanded the kingdom by conquering the kingdoms of Attingal, Kollam, Kayamkulam, Kottarakara, Kottayam, Changanassery, Meenachil, Poonjar and Ambalapuzha. In 1729, Marthanda Varma founded the princely state of Thiruvithamkoor and Thiruvananthapuram was made the capital in 1795 after shifting the capital from Padmanabhapuram in Kanyakumari district.[56] Thiruvananthapuram became a prominent city in Kerala under Marthanda Varma.[57]


A language map of India prepared in 1822.
As a result of the annexation of neighbouring chiefdoms, the artists and scholars from these places migrated to Thiruvananthapuram, turning it into a cultural center. Marthanda Varma gave patronage to different temple art forms including Koothu, Padhakam, Kathakali, Thullal, and Koodiyattam. Noted artists such as Ramapurathu Warrier and Kunchan Nambiar amongst others served as his court poets.[58] Travancore became the most dominant state in Kerala by defeating the powerful Zamorin of Kozhikode in the battle of Purakkad in 1755.[21]

The city developed into a significant intellectual and artistic centre during this period. The city's golden age was during the mid-19th century under the reign of Maharaja Swathi Thirunal and Maharaja Ayilyam Thirunal. This era saw the establishment of the first English school (1834), the Observatory (1837), the General Hospital (1839), the Oriental Research Institute & Manuscripts Library and the University College (1873). The first mental hospital in the state was started during the same period. Sanskrit College, Ayurveda College, Law College and a second-grade college for women were started by Moolam Thirunal (1885–1924).[59]

The early 20th century was an age of tremendous political and social changes in the city. The Sree Moolam Popular Assembly, established in 1904, was the first democratically elected legislative council in any Indian state.[60] Despite not being under the direct control of the British Empire at any time, the city featured prominently in India's freedom struggle. The Indian National Congress had a very active presence in Thiruvananthapuram. A meeting of the Indian National Congress presided by Dr Pattabhi Sitaramaiah was held here in 1938.


Kowdiar Palace built-in 1915 was the official residence of the Travancore Royal Family.[61]
The Thiruvananthapuram Municipality came into existence in 1920 as the first municipality in the Travancore region. The municipality was converted into a corporation on 30 October 1940, during the period of Chitra Thirunal Bala Rama Varma, who took over in 1931.[62] The city witnessed multi-faceted progress during his period. The promulgation of the "Temple Entry Proclamation" (1936) was an act that underlined social emancipation. This era also saw the establishment of the University of Travancore in 1937, which later became Kerala University.[63]

With the end of British rule in 1947, Travancore chose to join the Indian union. The first popularly elected ministry, headed by Pattom Thanu Pillai, was installed in office on 24 March 1948. In 1949, Thiruvananthapuram became the capital of Thiru-Kochi, the state formed by the integration of Travancore with its northern neighbour, the Kochi.[64] The king of Travancore, Chitra Thirunal Bala Rama Varma, became the Rajpramukh of the Travancore-Cochin Union from 1 July 1949 until 31 October 1956. When the state of Kerala was formed on 1 November 1956, Thiruvananthapuram became its capital.[65]

With the establishment of Thumba Equatorial Rocket Launching Station (TERLS) in 1962, Thiruvananthapuram became the cradle of India's ambitious space programme. The first Indian space rocket was developed and launched from the Vikram Sarabhai Space Centre (VSSC) in the outskirts of the city in 1963. Several establishments of the Indian Space Research Organisation (ISRO) were later established in Thiruvananthapuram.[66]

A significant milestone in the city's recent history was the establishment of Technopark—India's first IT park—in 1995.[67] Technopark has developed into the largest IT park in the geographical area,[68] employing around 62,000 people in 450 companies.[</p>
<h4>Geography</h4>
<p>Thiruvananthapuram is built on seven hills[70] by the seashore and is at 8.5°N 76.9°E on the west coast, near the southern tip of mainland India.[71] The city is on the west coast of India and is bounded by the Laccadive Sea to its west and the Western Ghats to its east. The average elevation of the city is 16 ft (4.9 m) above sea level.[72] The Geological Survey of India has identified Thiruvananthapuram as a moderately earthquake-prone urban centre and categorised the metropolis in the Seismic III Zone.[73] Thiruvananthapuram lies on the shores of Karamana and Killi rivers. Vellayani, Thiruvallam and Aakulam backwaters lie in the city.[74] The soil type in the middle part of the city is a dark brown loamy laterite soil high in phosphates. Laterisation is a result of the heavy rainfall and humid conditions. In western coastal regions of the city, sandy loam soil is found, and on hilly eastern parts of the district, rich dark brown loam of granite origin is found.[75]

The Thiruvananthapuram Corporation is spread over 214.86 km2 (82.96 sq mi).[3] The wider Thiruvananthapuram metropolitan area comprises Thiruvananthapuram corporation, three municipalities and 27 panchayats, as of 2011.[76] Being the largest city in India's southern tip region, it is essential for both military logistics and civil aviation in the southern part of the country. Thiruvananthapuram is the headquarters of the Southern Air Command (SAC) of the Indian Air Force.</p>
<h4>Climate</h4>
<p>The city has a climate that lies on the border between a tropical savanna climate (Köppen Aw) and a tropical monsoon climate (Am). As a result, its only distinct seasons relate to rainfall rather than temperature. The mean maximum temperature is 34 °C (93 °F) and the mean minimum temperature is 19 °C (66 °F). The humidity is high and rises to about 90% during the monsoon season.[78] Thiruvananthapuram is the first city along the path of the south-west monsoons and gets its first showers in early June. The city receives heavy rainfall of around 1,835 mm (72.2 in) per year. The city also gets rain from the receding north-east monsoons which hit the city by October. The dry season sets in by December. The lowest temperature recorded in the city core was 10.8 °C (51.4 °F) on 6 January 1974 and the highest temperature was 38.2 °C (100.8 °F) on 21 February 2019.[79] At the airport, the lowest temperature recorded was 12.1 °C (53.8 °F) on 15 January 1975 and the highest temperature was 36.3 °C (97.3 °F) on 5 May 1998</p>
      <h4>Demographics</h4>
      <p>According to provisional results of the 2011 national census, the Corporation of Thiruvananthapuram, which occupies an area of 214 km2 (83 sq mi), had a population of 957,730.[3] The city's population density was 4,454/km2 (11,540/sq mi).[3] The Urban Agglomeration had a population of 1,687,406 in 2011.[5] The sex ratio is 1,040 females for every 1,000 males, which is higher than the national average.[3] Thiruvananthapuram's literacy rate of 93.72%[86] exceeds the all-India average of 74%.[87]

It is a historical city where Malayali form the vast majority of Thiruvananthapuram's population. There are also minorities like the Tamils and North Indians residing here. According to the 2011 census, 68.5% of the population is Hindu, 16.7% Christians and 13.7% Muslims.[88] The remainder of the community includes Jains, Jews, Sikhs, Buddhists and other religions which account for 0.06% of the population; 0.85% did not state a belief in the census.[88]

Malayalam, the official state language, is the dominant language in Thiruvananthapuram City: English is also used, mainly by the white-collar workforce. Tamil has the most speakers after Malayalam. The city also has a few Tulu, Kannada, Konkani, Dhivehi, Telugu and Hindi speakers. As per the 2001 census, the population below the poverty line in the city was 11,667.[89]

Thiruvananthapuram has witnessed massive immigration of workers from northern India, mainly Punjab, Haryana, and Madhya Pradesh, and Eastern India, mainly West Bengal and Bihar, and from neighbouring countries like Sri Lanka, the Maldives, Nepal and Bangladesh.[9</p>
      <h4>Economy</h4>
      <p>Thiruvananthapuram's economy comprises Information Technology, education, plantations, aerospace, commerce and tourism.[117] Thiruvananthapuram district contributes 10.31%, of the state's GDP.[15] With an economic growth rate of 13.83%, Thiruvananthapuram is the fastest-growing district in Kerala.[15] Thiruvananthapuram was listed as one of the top ten cities in India on Vibrancy and Consumption Index by a study conducted by global financial services firm Morgan Stanley.[118] State- and central-government employees make up a large percentage of the city's workforce.[15] Thiruvananthapuram is a major aerospace research centre in India. The Vikram Sarabhai Space Centre, the most significant and leading centre of ISRO,[119] and several space-related, state-owned ISRO centres such as Thumba Equatorial Rocket Launching Station, Liquid Propulsion Systems Centre, and ISRO Inertial Systems Unit are based in Thiruvananthapuram.[120] The BrahMos Aerospace Trivandrum Limited is one of the leading missile integration and defence production units in India.[121] Other enterprises include Travancore Titanium Products, Kerala Automobiles Limited, MILMA, English Indian Clays, Keltron, Trivandrum Rubber Works and HLL Lifecare Limited.


A highway at Thiruvananthapuram
Thiruvananthapuram is a major IT and ITES hub in India. The city contributes about 40-45% of Kerala's total software exports.[15][122] Thiruvananthapuram houses major multinational Technology companies like Oracle Corporation, Nissan, Allianz Technology, Envestnet, Tata Consultancy Services, Infosys, UST Global, Ernst & Young, Flytxt, Navigant, Tata Elxsi, McKinsey & Company, RR Donnelly and Quest Global.[123] Technopark is the largest information-technology park in India in terms of built-up area.[124] It is the largest employment base campus in Kerala with 52,000 IT/ITES professionals and about 400 companies.[15][123] Other IT, media and industrial campuses include Kinfra Film and Video Park, Kinfra Apparel Park, B-HUB and Chithranjali Film Complex.[125][126] Other major IT, biotechnology and industrial campuses include Technocity, Bio 360 Life sciences park and Digital Science Park.[127][128]

Tourism is a significant economic sector.[129][130][131] The presence of natural attractions like beaches, backwaters, hills, and plantations and attractions like heritage, history, Ayurveda, medical tourism and knowledge centres attract many tourists.[132] The city experienced a surge of investment in the real estate, infrastructure and retail sectors in 2016–17.[133]

Port-related activity is low mainly due to the underdevelopment of ports. Vizhinjam International Seaport is a transhipment port under construction.[134] Vizhinjam port's location is close to the international shipping routes and, it is just 10–12 nautical miles from the busy Persian Gulf-Malacca shipping lane.[135] The port also has a natural depth of 18 to 20 metres which can accommodate huge container ships.[136] The berths at Vizhinjam port are designed to cater to vessels of up to 24,000 </p>
      <h4>Culture</h4>
      <p>Thiruvananthapuram is known as the "Evergreen City of India" because of its green landscapes and the presence of many public parks.[1][140] Thiruvananthapuram has historically been a cultural hub in Southern India due to the development of arts, architecture and liberal customs by the rulers of erstwhile Thiruvananthapuram. As a testimony to this, renowned artists like Maharaja Swathi Thirunal and Raja Ravi Varma hail from the city.[141][142] Prominent social reformers such as Sri Narayana Guru, Chattampi Swamikal, Ayyankali, Vakkom Moulavi and C. V. Raman Pillai also are from Thiruvananthapuram.[143]

Two of the three Malayalam triumvirate poets, Ulloor S. Parameswara Iyer and Kumaran Asan are from Thiruvananthapuram.[144][145] Annual literature festivals like the Kovalam Literary Festival, are held in the city.[146] Literary development is further aided by state institutions such as the State Central Library, one of the oldest public libraries in India, which was established in 1829,[147] and other major libraries including the Thiruvananthapuram Corporation Central library, and the Kerala University Library.[148] Thiruvananthapuram has been a hub of classical music since the days of Maharaja of Travancore, Swathi Thirunal.[149][150] Thiruvananthapuram is known for many music festivals like the Navarathri Music Festival, one of the oldest festivals of its kind in South India,[149] Swathi Sangeethotsavam, Soorya Music fest, Neelakanta Sivan Music Fest and many other music festivals are organised by various cultural groups.[149] The 111-day-long Soorya Festival is the biggest art and cultural event in Kerala.[151][152] The Soorya Festival features film festivals, theatre festivals, dance, music, painting and photography exhibitions.[151]


16th IFFK 2011 banner at Kairali Theater Complex
The Malayalam film Industry was started in Thiruvananthapuram. The first Malayalam feature film, Vigathakumaran directed by J. C. Daniel was released in Thiruvananthapuram.[153] J. C. Daniel is considered the father of Malayalam film industry. He also established the first film studio in Kerala, the Travancore National Pictures at Thiruvananthapuram in 1926.[154][155] The International Film Festival of Kerala (IFFK), which is held every year in December, is one of Asia's largest film festivals in terms of viewer participation.[156][157] In addition to various film festivals, the presence of the Central Board of Film Certification's regional office, many movie studios and production facilities like the Uma Studio, Chitranjali Studio, Merryland Studio, Kinfra Film and Video Park and Vismayas Max contribute to the growth of Thiruvananthapuram as a centre of cinema.[158][159]

Apart from the famous Padmanabhaswamy Temple, the city's architecture is championed by the Napier Museum and Thiruvananthapuram Zoo, one of the oldest zoos in India.[160] Other architectural landmarks include Kuthira Malika Palace, Kowdiar Palace, Attukal temple, Beemapally Mosque, Connemara Market, and the Mateer Memorial Church. Thiruvananthapuram was the main centre of Laurie Baker's architecture.[161]

Along with the major festivals of Onam, Vishu, Deepavali, and Navaratri, Christian and Islamic festivals like Christmas, Eid ul-Fitr, Bakrid and Milad-e-sheriff, the diverse ethnic populace of the city celebrates several local festivals like Attukal Pongala,[162] Beemapally Uroos,[163] Vettukaad Church Festival,[164] Padmanabhaswamy Temple Aaraattu and Lakshadeepam festival.[165] During the Onam festival, the state government conducts several cultural events for a week in the city.[166] The Attukal Pongala festival attracts millions of women devotees from across India and abroad. It is the largest gathering of women in the world.[167][168] Germany's Goethe Zentrum, France's Alliance Française and Russia's Gorky Bhavan centres host a wide range of events and programmes throughout the year.[169][170][171]

The general cuisine of the people is Keralite cuisine, which is generally characterised by an abundance of coconut and spices. Other South Indian cuisines, as well as Chinese and North Indian cuisines, are popular.[172] Thiruvananthapuram has many restaurants offering Arabic, Italian, Thai and Mexican cuisines</p>
       <h3>Transport</h3>
       <p> <h4>Public transport</h4>

A KSRTC Double-decker bus in the city
The majority of bus services are conducted by government operators. There are also private operators.[175] The city buses operated by Kerala State Road Transport Corporation (KSRTC) are an important and reliable means of public transport available in the city. The main bus stations in the city are the Central Bus Station in Thampanoor, where most of the long-distance buses ply from, and the city bus station in East Fort, where most city buses ply from.[176][177] Three-wheeled, yellow and black auto-rickshaws and taxis, are other popular forms of public transport.[178][179] Thiruvananthapuram Light Metro is a fully elevated metro rail – rapid transit system planned to ease the congestion in the city.[180][181]

<h4>Road </h4>
Thiruvananthapuram has a well-developed road transport infrastructure.[180] The roads in the city are maintained by the Thiruvananthapuram Roads Development Company Limited (TRDCL) and Kerala PWD.[182] TRDCL manages the 42 km city roads which come under the Thiruvananthapuram City Roads Improvement Project (TRCIP), which is the first urban road project in India.[183][184] TRCIP is a Public-private partnership project to improve and maintain the existing road network in the city to cater to the needs of rapid urbanisation.[183] TRCIP has won the International Road Federation's Global Road Achievement Awards in 2015.[185] TCRIP has also been selected by United Nations as a replicable Public Private Partnership model.[186] It was one of the 12 Public-private partnership project case studies from across the world which fulfil the Sustainable Development Goals of the UN Agenda 2030.[187][188]

Thiruvananthapuram is served by National Highway 66 of India's National Highways system.[189] The city is connected to the North-South Corridor of the National Highway system at Aralvaimozhi, which is 80 km south of the city.[190] The State Highway 1, which commonly known as the Main Central Road is an arterial highway in the city. Other major highways in the city are State Highway 2 and State Highway 45.[191] The Mahatma Gandhi Road is the main arterial road in the city.[192][193] Another important road is the Kowdiar Road, which is also known as the Royal Road, as it leads to the Kowdiar Palace.[194]

  <h4>Rail</h4>
Thiruvananthapuram is a divisional headquarters in the Southern Railway zone of the Indian Railways.[195] Long-distance trains originate from Thiruvananthapuram Central and Kochuveli railway terminals. Kochuveli railway terminal is developed to ease congestion on the central station and it acts as a satellite station to Thiruvananthapuram Central.[196] Thiruvananthapuram Central is the busiest railway station in Kerala.[197] Other railway stations in the city are Thiruvananthapuram Pettah, Nemom railway station, Veli railway station and Kazhakoottam railway station. Being the southernmost municipal corporation in India, many long train services of Indian Railways originate from Thiruvananthapuram like Trivandrum Rajdhani Express, Thiruvananthapuram - Silchar Superfast Express and Kochuveli - Amritsar Weekly Express. There are plans to develop a railway terminal at Nemom railway station to reduce congestion at Thiruvananthapuram Central.[198]

<h4>Air </h4>
Thiruvananthapuram is served by the Thiruvananthapuram International Airport, located at Chakai, only 6.7 km (4.2 mi) from the city centre. The airport started operations in 1935 and is the first airport in Kerala.[199] Being one of the gateways to the state, it has direct connectivity to all the major cities in India as well as the Middle East, Malaysia, Singapore, the Maldives and Sri Lanka. As the city is headquarters of the Southern Air Command (SAC) of the Indian Air Force, Thiruvananthapuram International Airport caters to the Indian Air Force (IAF) and the Coast Guard for their strategic operations.[200] IAF has an exclusive apron to handle all their operations. The airport also caters to the Rajiv Gandhi Academy for Aviation Technology which carries out pilot-training activities.[201]

 <h4>Sea</h4>
Small cruise ships often dock at Vizhinjam Harbour.[202] A cruise terminal is under trial run at Vizhinjam Transshipment Terminal and some of the world's largest container vessels had already docked here.[203][204] Vizhinjam seaport has been designated by the government as an authorised immigration check-post for entry and exit from India for international ships and cruises.</p>
      
      <h1>MAJOR ATTRACTIONS</h1>
      <IMG>
        <img height={"450px"} width={"400px"}style={{marginTop:"80px"}} src="https://i.pinimg.com/736x/c6/e3/3e/c6e33e73a41c294022a85f7f099ff7d7.jpg" alt="" />
<img height={"450px"} width={"400px"}style={{marginTop:"80px"}} src="https://www.dtpcthiruvananthapuram.com/uploads/picture_gallery/gallery_images/kovalam-1920x1080-20230510231440820551.webp" alt="" />
<img height={"450px"} width={"400px"}style={{marginTop:"80px"}} src="https://i.ytimg.com/vi/ONUMTzP3BRw/hqdefault.jpg" alt="" />
<img height={"450px"} width={"400px"}style={{marginTop:"80px"}} src="https://play-lh.googleusercontent.com/kVIgbUYxQ06BZIg_9z-iTWyZ74XSSUwkbqMFLFSCd_jSB1WXJPep0fKbLlmnn77CPsMM" alt="" />
<img height={"450px"} width={"400px"}style={{marginTop:"80px"}} src="https://i0.wp.com/beemapally.org/wp-content/uploads/2021/08/beemapally001.jpg?ssl=1" alt="" />
<img height={"450px"} width={"400px"}style={{marginTop:"80px"}} src="https://i.ytimg.com/vi/U7nBnw-TSo8/hqdefault.jpg" alt="" />
</IMG>
<div style={{height:"350px",paddingLeft:"500px",paddingTop:"100px",backgroundColor:'red'}}>
      <h2>contact us for more informations</h2>

    </div>
    </div>
  )
}

export default Trivandrum
